language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

env:
  matrix:
    - TARGET=CI

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'
    - '$HOME/.sonar'

notifications:
  email: false
  webhooks:
    - secure: "QmckyMLPFVrOaIL9fVLfrQcOTO8VTL0sflvvT6lyf4Vxb/YuL5sSBWBltZWwATmfImYczeH5IR6VDiu+69dsOtqJSKZUsz5XN26ljFZr5jj4i+hxVT5qqW0woM5IeTqeKbUHmi7Vwt31IknMVcltthhc+9zm0T5Z6JZm2shqYYo="
